name: 'Sets project up'
description: 'Configura a versão do Node, permissões e instala dependências'

runs:
  using: "composite"
  steps:
    - name: webfactory/ssh-agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Read Node.js version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
      shell: bash

    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

    - name: Create ~/.npmrc file (for private packages)
      run: echo //npm.pkg.github.com/:_authToken=${{ inputs.token }} >> ~/.npmrc |
        echo @warrenbrasil:registry=https://npm.pkg.github.com/ >> ~/.npmrc
      shell: bash

    - name: Restore yarn cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ steps.nvm.outputs.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn
    - name: Installing application dependencies
      run: yarn install
      shell: bash