name: 'Sets project up'
description: 'Configura a versão do Node, permissões e instala dependências'

inputs:
  token:
    description: The Github PAT
    required: true

runs:
  using: "composite"
  steps:
    name: Use personal token
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FIRST_NAME: Mona
        LAST_NAME: Octocat

    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
        submodules: 'true'

    - name: Read Node.js version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      id: nvm
      shell: bash

    - name: Use Node.js ${{ steps.nvm.outputs.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}

    - name: Create ~/.npmrc file (for private packages)
      run: echo //npm.pkg.github.com/:_authToken=${{ inputs.token }} >> ~/.npmrc |
        echo @warrenbrasil:registry=https://npm.pkg.github.com/ >> ~/.npmrc
      shell: bash

    - name: Restore yarn cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ steps.nvm.outputs.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn
    - name: Installing application dependencies
      run: yarn install
      shell: bash