name: Linter and unit testing

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN  }}
          submodules: 'true'

      - name: Setup project
        uses: ./.github/workflows/setup/
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Lint
        run: yarn lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN  }}
          submodules: 'true'
        env: 
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Setup project
        uses: ./.github/workflows/setup/
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Unit tests
        run: yarn test