name: Linter and unit testing

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WARREN }}
          submodules: 'true'

      - name: Setup project
        uses: ./.github/workflows/setup/
        with:
          token: ${{ secrets.WARREN }}

      - name: Lint
        run: yarn lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WARREN }}
          submodules: 'true'

      - name: Setup project
        uses: ./.github/workflows/setup/
        with:
          token: ${{ secrets.WARREN }}

      - name: Unit tests
        run: yarn test
