name: Linter and unit testing

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup project
        uses: ./.github/workflows/setup/

      - name: Lint
        run: yarn lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Setup project
        uses: ./.github/workflows/setup/

      - name: Unit tests
        run: yarn test