name: Run Unit Tests and Lint Files
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/workflows/setup/

      - name: Lint
        run: yarn lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Setup project
        uses: ./.github/workflows/setup/

      - name: Unit tests
        run: yarn test
