name: Linter and unit testing

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: Setup project
        uses: ./.github/workflows/setup/
        with:
          token: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: Lint
        run: yarn lint

  test-unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: Setup project
        uses: ./.github/workflows/setup/
        with:
          token: ${{ secrets.SSH_PRIVATE_KEY  }}

      - name: Unit tests
        run: yarn test